# Generated by Django 6.0.4 on 2026-05-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media_assets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
