# Generated by Django 6.0.4 on 2026-05-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_media_assets_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media_assets',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of media URLs, e.g. ["https://...", "https://..."].'),
        ),
    ]
