# Generated by Django 4.2.7 on 2026-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_media_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Project cover image. Will be stored in S3 if configured.', null=True, upload_to='projects/covers/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, help_text='Skill icon image.', null=True, upload_to='skills/icons/'),
        ),
    ]
