# Generated by Django 4.2.7 on 2026-05-18 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_project_cover_image_skill_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Project cover image. Will be stored in S3 if configured.",
                null=True,
                upload_to="projects/covers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Skill icon image.",
                null=True,
                upload_to="skills/icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "svg"]
                    )
                ],
            ),
        ),
    ]
