# Generated by Django 4.2.7 on 2026-05-27 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_user_abstractbaseuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeCertification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("icon", models.CharField(default="verified", max_length=64)),
                ("meta", models.CharField(blank=True, max_length=200, null=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "resume_certifications",
            },
        ),
    ]
