# Generated by Django 6.0.4 on 2026-05-09 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSetting',
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=255)),
                ('site_subtitle', models.CharField(max_length=512)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('social_links', models.JSONField(default=list)),
                ('contact_email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/favicon')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='settings/header_image')),
                ('footer_image', models.ImageField(blank=True, null=True, upload_to='settings/footer_image')),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
    ]
