# Generated by Django 4.2.7 on 2026-05-18 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_settings_delete_appsetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="settings/favicon",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "svg", "ico"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="footer_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="settings/footer_image",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "svg", "ico"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="header_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="settings/header_image",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "svg", "ico"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="settings/logo",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "svg", "ico"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="site_subtitle",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
