# Generated by Django 4.2.7 on 2026-05-01 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=220, null=True)),
                ('message', models.TextField()),
                ('source_page', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contact_inquiries',
            },
        ),
    ]
