# Generated by Django 4.2.7 on 2026-05-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_auth", "0002_alter_user_role_alter_user_status_and_more"),
    ]

    operations = [
        # Rename password_hash → password so existing hashed passwords are preserved.
        migrations.RenameField(
            model_name="user",
            old_name="password_hash",
            new_name="password",
        ),
        # AbstractBaseUser's password field is CharField(max_length=128).
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        # AbstractBaseUser adds last_login; we keep our custom last_login_at too.
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
