import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#c0c1ff",
        "tertiary-container": "#00885d",
        "surface-container": "#171f33",
        "on-surface-variant": "#c7c4d7",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary-fixed": "#07006c",
        "on-surface": "#dae2fd",
        outline: "#908fa0",
        "on-tertiary-fixed": "#002113",
        tertiary: "#4edea3",
        "on-error": "#690005",
        "tertiary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-container": "#0d0096",
        "on-tertiary-fixed-variant": "#005236",
        "surface-variant": "#2d3449",
        "on-tertiary-container": "#000703",
        primary: "#c0c1ff",
        secondary: "#4cd7f6",
        "on-secondary": "#003640",
        "inverse-on-surface": "#283044",
        "surface-container-highest": "#2d3449",
        "on-secondary-fixed-variant": "#004e5c",
        "outline-variant": "#464554",
        "secondary-container": "#03b5d3",
        "secondary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed": "#001f26",
        "primary-container": "#8083ff",
        "inverse-primary": "#494bd6",
        "inverse-surface": "#dae2fd",
        error: "#ffb4ab",
        "on-background": "#dae2fd",
        "primary-fixed": "#e1e0ff",
        "error-container": "#93000a",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "on-secondary-container": "#00424e",
        "surface-container-low": "#131b2e",
        "surface-container-high": "#222a3d",
        "secondary-fixed": "#acedff",
        surface: "#0b1326",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-lowest": "#060e20",
        "on-primary": "#1000a9",
        "on-tertiary": "#003824",
        background: "#0b1326",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "margin-desktop": "64px",
        "container-max": "1440px",
        gutter: "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "display-lg": ["Space Grotesk", "sans-serif"],
        "label-mono": ["ui-monospace", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "space-grotesk": ["Space Grotesk", "sans-serif"],
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontSize: {
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-mono": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-sm": [
          "14px",
          { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-base": [
          "16px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [forms, containerQueries],
};
